// ============================================================
// SessionPage.jsx — Analytics + Chat UI for a single session
// ============================================================
import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell
} from 'recharts';
import { ArrowLeft, Send, Trash2, Bot, User, BarChart2, MessageSquare, Info } from 'lucide-react';
import { sessionAPI, analyticsAPI, chatAPI, userAPI } from '../api';
import { useAuth } from '../hooks/useAuth.jsx';
import GuideModal from '../components/GuideModal';
import './SessionPage.css';

const AI_DISCLAIMER = '⚠️ AI answers are generated by a language model and may not be 100% accurate. Always verify important information.';

const CHART_COLORS = ['#25d366','#818cf8','#f59e0b','#f87171','#34d399','#60a5fa','#fb923c','#a78bfa'];

export default function SessionPage() {
  const { id }   = useParams();
  const navigate = useNavigate();

  const [session,   setSession]   = useState(null);
  const [activeTab, setActiveTab] = useState('overview');  // 'overview' | 'chat'
  const [analytics, setAnalytics] = useState({});
  const [loading,   setLoading]   = useState(true);
  const [guideContext, setGuideContext] = useState(null);
  const [isOffline, setIsOffline] = useState(!navigator.onLine);
  
  const { user, setUser } = useAuth();
  const [selectedModel, setSelectedModel] = useState(user?.preferred_model || 'gemini/gemini-flash');

  // Offline detection
  useEffect(() => {
    const handleOnline = () => setIsOffline(false);
    const handleOffline = () => setIsOffline(true);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  // Handle Model Change directly in chat
  async function handleModelChange(e) {
    const newModel = e.target.value;
    setSelectedModel(newModel);
    try {
      const res = await userAPI.updateSettings({ preferred_model: newModel });
      setUser(prev => ({ ...prev, preferred_model: newModel }));
      localStorage.setItem('user', JSON.stringify({ ...user, preferred_model: newModel }));
    } catch {
      // Revert on failure
      setSelectedModel(user?.preferred_model || 'gemini/gemini-flash');
    }
  }

  // Chat state
  const [messages,    setMessages]    = useState([]);
  const [input,       setInput]       = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const chatEndRef = useRef(null);

  // DLP Password Challenge State
  const [passwordModalOpen, setPasswordModalOpen] = useState(false);
  const [pendingQuestion, setPendingQuestion] = useState('');
  const [modalPassword, setModalPassword] = useState('');
  const [modalError, setModalError] = useState('');
  const [wrongPasswordCount, setWrongPasswordCount] = useState(0); // Security feature

  // Scroll chat to bottom on new message
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const loadAllAnalytics = useCallback(async () => {
    try {
      const results = await Promise.allSettled([
        analyticsAPI.overview(id),
        analyticsAPI.participants(id),
        analyticsAPI.timeline(id, 'daily'),
        analyticsAPI.peakHours(id),
        analyticsAPI.wordFrequency(id, 20),
        analyticsAPI.emojiFrequency(id),
        analyticsAPI.mediaLinks(id),
        analyticsAPI.responseTime(id),
      ]);

      results.forEach((r, idx) => {
        if (r.status === 'rejected') {
          console.error(`Analytics fetch failed for index ${idx}:`, r.reason);
        }
      });

      const [overview, participants, timeline, peakHours, words, emojis, media, responseTime] = results;

      setAnalytics({
        overview:     overview.value?.data?.data,
        participants: participants.value?.data?.data?.map(p => ({ ...p, message_count: Number(p.message_count) })),
        timeline:     timeline.value?.data?.data?.map(t => ({ ...t, message_count: Number(t.message_count) })),
        peakHours:    peakHours.value?.data?.data,
        words:        words.value?.data?.data?.map(w => ({ ...w, frequency: Number(w.frequency) })),
        emojis:       emojis.value?.data?.data?.map(e => ({ ...e, frequency: Number(e.frequency) })),
        media:        media.value?.data?.data,
        responseTime: responseTime.value?.data?.data,
      });
    } catch {
      // Catch blocks still needed just in case
    }
  }, [id]);

  const loadSession = useCallback(async () => {
    try {
      const res = await sessionAPI.get(id);
      setSession(res.data.session);
      // Load all analytics in parallel
      loadAllAnalytics();
    } catch {
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  }, [id, navigate, loadAllAnalytics]);

  const loadChatHistory = useCallback(async () => {
    try {
      const res = await chatAPI.getHistory(id);
      // Convert history entries to flat message pairs
      const msgs = [];
      for (const h of res.data.history) {
        msgs.push({ role: 'user',      text: h.question,  time: h.created_at });
        msgs.push({ role: 'assistant', text: h.answer, engine: h.engine_used, modelUsed: h.modelUsed, time: h.created_at });
      }
      setMessages(msgs);
    } catch {
      // no history yet
    }
  }, [id]);

  // Load session + analytics on mount
  useEffect(() => {
    loadSession();
    loadChatHistory();
  }, [loadSession, loadChatHistory]);

  const { logout } = useAuth(); // Import logout for security rule

  async function handleSend() {
    const q = input.trim();
    if (!q || chatLoading) return;

    setInput('');
    setMessages(prev => [...prev, { role: 'user', text: q, time: new Date().toISOString() }]);
    setChatLoading(true);

    try {
      const res = await chatAPI.ask(id, q);
      const { answer, engine, modelUsed } = res.data;
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: answer,
        engine: engine,
        modelUsed: modelUsed,
        time: new Date().toISOString(),
      }]);
    } catch (err) {
      if (err.response?.status === 403 && err.response?.data?.requiresPassword) {
        // Intercepted by DLP Guardrail
        setMessages(prev => prev.slice(0, -1)); // Revert optimistic bubble
        setPendingQuestion(q);
        setPasswordModalOpen(true);
        setModalError('');
        setModalPassword('');
        setWrongPasswordCount(0); // Reset count when opened
      } else {
        setMessages(prev => [...prev, {
          role: 'assistant',
          text: err.response?.data?.error || 'Something went wrong. Please try again.',
          engine: 'error',
          time: new Date().toISOString(),
        }]);
      }
    } finally {
      setChatLoading(false);
    }
  }

  async function handleVerifyPassword() {
    if (!modalPassword) return;
    setModalError('');
    setPasswordModalOpen(false); // Optimistically close
    setMessages(prev => [...prev, { role: 'user', text: pendingQuestion, time: new Date().toISOString() }]);
    setChatLoading(true);

    try {
      const res = await chatAPI.ask(id, pendingQuestion, modalPassword);
      const { answer, engine, modelUsed } = res.data;
      setMessages(prev => [...prev, {
        role: 'assistant',
        text: answer,
        engine: engine,
        modelUsed: modelUsed,
        time: new Date().toISOString(),
      }]);
      setModalPassword('');
    } catch (err) {
      setMessages(prev => prev.slice(0, -1)); // Revert optimistic bubble
      if (err.response?.status === 403 && err.response?.data?.error === 'Incorrect password.') {
        const newCount = wrongPasswordCount + 1;
        if (newCount >= 2) {
          // Security Trigger: 2 wrong passwords = Logout
          setPasswordModalOpen(false);
          logout();
          navigate('/login', { replace: true });
          return;
        }
        setWrongPasswordCount(newCount);
        setModalError(`Incorrect password. Attempt ${newCount} of 2.`);
        setPasswordModalOpen(true); // Re-open
      } else {
        setMessages(prev => [...prev, {
          role: 'assistant',
          text: err.response?.data?.error || 'Something went wrong. Please try again.',
          engine: 'error',
          time: new Date().toISOString(),
        }]);
      }
    } finally {
      setChatLoading(false);
    }
  }

  async function handleClearHistory() {
    if (!window.confirm('Clear all chat history for this session?')) return;
    try {
      await chatAPI.clearHistory(id);
      setMessages([]);
    } catch { /* ignore */ }
  }

  if (loading) return (
    <div className="page-center">
      <div className="spinner" style={{ width: 36, height: 36 }} />
    </div>
  );

  const ov = analytics.overview;

  return (
    <div className="session-page">
      {/* ── Header ── */}
      <header className="session-header">
        <button className="btn btn-secondary btn-sm" onClick={() => navigate('/dashboard')}>
          <ArrowLeft size={14} /> Dashboard
        </button>
        <div className="session-header-title">
          <h1 className="session-name">{session?.name}</h1>
          <span className="badge badge-green">
            {Number(session?.message_count).toLocaleString()} messages
          </span>
        </div>
        <div className="session-tabs">
          <button
            className={`tab-btn ${activeTab === 'overview' ? 'active' : ''}`}
            onClick={() => setActiveTab('overview')}
          >
            <BarChart2 size={15} /> Analytics
          </button>
          <button
            className={`tab-btn ${activeTab === 'chat' ? 'active' : ''}`}
            onClick={() => setActiveTab('chat')}
          >
            <MessageSquare size={15} /> Chat
          </button>
        </div>
      </header>

      {/* ── Analytics Tab ── */}
      {activeTab === 'overview' && (
        <div className="analytics-pane fade-in">
          <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '1rem' }}>
            <button className="btn-icon" onClick={() => setGuideContext('analytics')} title="Help with Analytics">
              <Info size={16} /> How to read these charts
            </button>
          </div>
          {/* Overview Stats */}
          {ov && (
            <div className="stats-row">
              {[
                { label: 'Total Messages',  val: Number(ov.total_messages || 0).toLocaleString() },
                { label: 'Participants',    val: ov.participant_count || '—' },
                { label: 'Days Active',     val: ov.duration_days || '—' },
                { label: 'Media Shared',    val: Number(ov.media_count || 0).toLocaleString() },
              ].map((s, i) => (
                <div key={i} className="stat-card">
                  <div className="stat-card-val">{s.val ?? '—'}</div>
                  <div className="stat-card-label">{s.label}</div>
                </div>
              ))}
            </div>
          )}

          {/* Timeline Chart */}
          {analytics.timeline?.length > 0 && (
            <div className="chart-card">
              <h3 className="chart-title">Messages Over Time</h3>
              <ResponsiveContainer width="100%" height={200}>
                <LineChart data={analytics.timeline}>
                  <XAxis dataKey="period" tick={{ fill: '#475569', fontSize: 11 }} tickLine={false}
                    tickFormatter={p => new Date(p).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} />
                  <YAxis tick={{ fill: '#475569', fontSize: 11 }} tickLine={false} axisLine={false} />
                  <Tooltip
                    contentStyle={{ background: '#1e2230', border: '1px solid #ffffff12', borderRadius: 8, fontSize: 12 }}
                    labelStyle={{ color: '#94a3b8' }}
                    itemStyle={{ color: '#25d366' }}
                    labelFormatter={p => new Date(p).toLocaleDateString()}
                  />
                  <Line type="monotone" dataKey="message_count" stroke="#25d366" strokeWidth={2} dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          )}

          <div className="charts-grid">
            {/* Peak Hours */}
            {analytics.peakHours?.length > 0 && (
              <div className="chart-card">
                <h3 className="chart-title">Peak Hours</h3>
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={analytics.peakHours} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <XAxis dataKey="hour" tick={{ fill: '#475569', fontSize: 10 }} tickLine={false}
                      tickFormatter={h => `${h}:00`} />
                    <YAxis hide />
                    <Tooltip
                      contentStyle={{ background: '#1e2230', border: '1px solid #ffffff12', borderRadius: 8, fontSize: 12 }}
                      formatter={(v) => [v, 'Messages']}
                      labelFormatter={h => `${h}:00 – ${h}:59`}
                    />
                    <Bar dataKey="message_count" fill="#25d366" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            )}

            {/* Participants Pie */}
            {analytics.participants?.length > 0 && (
              <div className="chart-card">
                <h3 className="chart-title">Message Share</h3>
                <ResponsiveContainer width="100%" height={220}>
                  <PieChart margin={{ top: 10, right: 10, bottom: 10, left: 10 }}>
                    <Pie
                      data={analytics.participants}
                      dataKey="message_count"
                      nameKey="sender_name"
                      cx="50%" cy="50%"
                      outerRadius={60}
                      label={({ payload, percent }) => {
                        const displayName = payload?.sender_name || payload?.name || '';
                        return `${displayName.split(' ')[0]} ${(percent*100).toFixed(0)}%`;
                      }}
                      labelLine={false}
                    >
                      {analytics.participants.map((_, i) => (
                        <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip contentStyle={{ background: '#1e2230', border: '1px solid #ffffff12', borderRadius: 8, fontSize: 12 }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            )}

            {/* Top Words */}
            {analytics.words?.length > 0 && (
              <div className="chart-card">
                <h3 className="chart-title">Top Words</h3>
                <div className="word-cloud">
                  {analytics.words.slice(0, 15).map((w, i) => (
                    <span
                      key={i}
                      className="word-tag"
                      style={{ fontSize: `${Math.max(0.7, Math.min(1.4, 0.7 + (w.frequency / analytics.words[0].frequency) * 0.7))}rem` }}
                    >
                      {w.word}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Top Emojis */}
            {analytics.emojis?.length > 0 && (
              <div className="chart-card">
                <h3 className="chart-title">Top Emojis</h3>
                <div className="emoji-list">
                  {analytics.emojis.slice(0, 8).map((e, i) => (
                    <div key={i} className="emoji-row">
                      <span className="emoji-char">{e.emoji}</span>
                      <div className="emoji-bar-wrap">
                        <div
                          className="emoji-bar"
                          style={{ width: `${(e.frequency / analytics.emojis[0].frequency) * 100}%` }}
                        />
                      </div>
                      <span className="emoji-count">{Number(e.frequency).toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Response Times */}
            {analytics.responseTime?.length > 0 && (
              <div className="chart-card">
                <h3 className="chart-title">Avg Response Time</h3>
                <div className="response-list">
                  {analytics.responseTime.map((r, i) => (
                    <div key={i} className="response-row">
                      <span className="response-name">{r.sender_name}</span>
                      <span className="response-time">
                        {r.avg_response_minutes < 60
                          ? `${Math.round(r.avg_response_minutes)}m`
                          : `${(r.avg_response_minutes / 60).toFixed(1)}h`}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Chat Tab ── */}
      {activeTab === 'chat' && (
        <div className="chat-pane fade-in">
          {/* Chat messages */}
          <div className="chat-messages">
            {messages.length === 0 && (
              <div className="chat-empty">
                <Bot size={40} style={{ opacity: 0.3 }} />
                <p><strong>Ask anything about this chat!</strong></p>
                <p>Examples: "Who sent the most messages?", "What was the most active day?", "Summarize the mood of this chat"</p>
                <div className="chat-disclaimer">
                  <Info size={13} /> {AI_DISCLAIMER}
                </div>
              </div>
            )}

            {messages.map((msg, i) => (
              <div key={i} className={`chat-bubble ${msg.role}`}>
                <div className="chat-bubble-icon">
                  {msg.role === 'user'
                    ? <User size={14} />
                    : <Bot size={14} />}
                </div>
                <div className="chat-bubble-content">
                  <div className="chat-bubble-text">{msg.text}</div>
                  {msg.role === 'assistant' && msg.engine && (
                    <div className="chat-bubble-meta">
                      <span className={`badge ${msg.engine === 'ai' ? 'badge-purple' : 'badge-green'}`}>
                        {msg.engine === 'ai' ? `🤖 AI ${msg.modelUsed ? '('+msg.modelUsed.split('/').pop()+')' : ''}` : '📊 Analytics'}
                      </span>
                      {msg.engine === 'ai' && (
                        <span className="chat-disclaimer-inline">
                          <Info size={10} /> May not be 100% accurate
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}

            {chatLoading && (
              <div className="chat-bubble assistant">
                <div className="chat-bubble-icon"><Bot size={14} /></div>
                <div className="chat-bubble-content">
                  <div className="chat-typing">
                    <span /><span /><span />
                  </div>
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          {/* Input bar */}
          <div className="chat-input-bar">
            {messages.length > 0 && (
              <button className="btn btn-secondary btn-sm" id="clear-chat-btn" onClick={handleClearHistory} title="Clear history" disabled={chatLoading}>
                <Trash2 size={13} />
              </button>
            )}
            <button className="btn-icon" onClick={() => setGuideContext('chat')} title="What can I ask?" style={{ marginRight: '0.5rem' }}>
              <Info size={18} />
            </button>
            <select
              className="input"
              value={selectedModel}
              onChange={handleModelChange}
              disabled={isOffline || chatLoading}
              style={{ padding: '0.4rem', fontSize: '0.8rem', maxWidth: '120px' }}
              title="Select AI Model"
            >
              <option value="gemini/gemini-flash">Gemini Flash</option>
              <option value="openai/gpt-4o">GPT-4o</option>
              <option value="anthropic/claude-3-haiku">Claude Haiku</option>
            </select>
            <input
              className="input chat-input"
              id="chat-input"
              type="text"
              placeholder={isOffline ? "AI offline. Ask a rule-based question (e.g. 'how many messages')" : "Ask something about this chat..."}
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && !e.shiftKey && handleSend()}
              disabled={chatLoading}
              autoFocus
            />
            <button
              className="btn btn-primary"
              id="chat-send-btn"
              onClick={handleSend}
              disabled={!input.trim() || chatLoading}
            >
              {chatLoading ? <span className="spinner" /> : <Send size={15} />}
            </button>
          </div>
        </div>
      )}

      <GuideModal
        isOpen={!!guideContext}
        onClose={() => setGuideContext(null)}
        context={guideContext}
      />

      {/* ── Password Challenge Modal ── */}
      {passwordModalOpen && (
        <div className="modal-overlay" onClick={() => setPasswordModalOpen(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <h3>Sensitive Information Detected</h3>
            <p className="modal-warning">
              You are asking for sensitive information. For your security, please verify your account password to proceed.
            </p>
            
            <div className="form-group" style={{ marginTop: '1rem', textAlign: 'left' }}>
              <label htmlFor="dlp-pwd" className="label">Account Password:</label>
              <input
                id="dlp-pwd"
                type="password"
                className="input"
                value={modalPassword}
                onChange={e => setModalPassword(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleVerifyPassword()}
                placeholder="Enter password"
                autoFocus
              />
            </div>
            
            {modalError && <div className="error-text" style={{ marginTop: '0.5rem' }}>{modalError}</div>}
            
            <div className="modal-actions" style={{ marginTop: '1.5rem' }}>
              <button className="btn btn-secondary" onClick={() => setPasswordModalOpen(false)}>
                Cancel
              </button>
              <button className="btn btn-primary" onClick={handleVerifyPassword} disabled={!modalPassword}>
                Verify & Continue
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
